version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.7.4
    working_directory: ~/wct_app
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "requirements.txt" }}
        - v1-dependencies-
    - run:
        name: install dependencies
        command: |
          sudo apt install python3 python3-pip python3-pytest pylint3 gunicorn3 python3-flask
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt
    - save_cache:
        paths:
        - ./venv
        key: v1-dependencies-{{ checksum "requirements.txt" }}
    - run:
        name: "Setup custom environment variables"
        command: |
          echo 'export WCT_VERSION="1.2.3"' >> $BASH_ENV # Redirect WCT_VERSION into $BASH_ENV
          echo 'export SECRET_SAUCE="2"' >> $BASH_ENV # Redirect SECRET_SAUCE into $BASH_ENV
          echo 'export PATH_TO_DATA_FILE="~/wct_app/data"' >> $BASH_ENV # Redirect PATH_TO_DATA_FILE into $BASH_ENV
      # Run a step to print what branch our code base is on.
    - run: # test what branch we're on.
        name: "What branch am I on?"
        command: echo ${CIRCLE_BRANCH}
      # Run another step, the same as above; note that you can
      # invoke environment variable without curly braces.
    - run:
        name: "What branch am I on now?"
        command: echo $CIRCLE_BRANCH
    - run:
        name: "What was my custom environment variable?"
        command: |
          echo ${WCT_VERSION}
          echo ${SECRET_SAUCE}
          echo ${PATH_TO_DATA_FILE}
          pwd
          ls
    - run:
        name: run tests
        command: |
          pylint3 --version
          ls -la **/*.py
          rm **/__init__.py
          ls -la **/*.py
          cd ~/wct_app/..
          pylint3 --errors-only **/*.py
          pytest-3 --disable-warnings --quiet tests/wct_tests.py
    - store_artifacts:
        path: test-reports
        destination: test-reports
workflows:
  version: 2
  workflow:
    jobs:
    - build
